# Generated by Django 4.2.7 on 2026-01-20 10:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import djangoapp.documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=255)),
                ('file', models.FileField(upload_to=djangoapp.documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('license', models.CharField(choices=[('cc0', 'CC0 - Public Domain'), ('cc-by', 'CC BY - Attribution'), ('cc-by-sa', 'CC BY-SA - Attribution-ShareAlike'), ('cc-by-nd', 'CC BY-ND - Attribution-NoDerivs'), ('cc-by-nc', 'CC BY-NC - Attribution-NonCommercial'), ('cc-by-nc-sa', 'CC BY-NC-SA - Attribution-NonCommercial-ShareAlike'), ('cc-by-nc-nd', 'CC BY-NC-ND - Attribution-NonCommercial-NoDerivs'), ('other', 'Other')], default='cc-by', max_length=20)),
                ('license_details', models.TextField(blank=True, help_text='Additional license information')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='categories.category')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='documents_status_e99d0b_idx'), models.Index(fields=['category', 'status'], name='documents_categor_053d3d_idx'), models.Index(fields=['slug'], name='documents_slug_6a0040_idx')],
            },
        ),
    ]
